# Generated by Django 4.1.11 on 2023-09-21 08:38

from django.db import migrations, models
import django.db.models.deletion

def add_default_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')  # Replace 'api' with the app name where Role model is defined
    Role.objects.create(name='admin')
    Role.objects.create(name='livreur')
    Role.objects.create(name='user')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dujour', models.BooleanField(default=False)),
                ('dessert', models.BooleanField(default=False)),
                ('prix', models.IntegerField()),
                ('ingredient', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('tel', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('roles', models.ManyToManyField(blank=True, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.IntegerField()),
                ('etat', models.CharField(max_length=100)),
                ('plats', models.ManyToManyField(to='api.plat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('userlivreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livreur')),
            ],
        ),

        # Add default roles : admin, livreur,  user
        migrations.RunPython(add_default_roles),
    ]
