# Generated by Django 4.1.11 on 2023-09-21 21:30

from django.db import migrations

def add_default_users(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.create(
        nom='Michel',
        prenom='exemple',
        adresse='4 rue de la paix',
        mail='email1@example.com',
        photo="",
        tel='1234567891',
        password="$2b$12$1jzTWSVNlOvfjvu3jkCMVuT1sfhMODdmJEtfTiMN/VPO82Px90qNa",
    )
    
    User.objects.create(
        nom='Kevin',
        prenom='autre',
        adresse='5 avenue de paris',
        mail='email2@example.com',
        photo="",
        tel='1234567892',
        password='motdepassepardefaut2',
    )

    User.objects.create(
        nom='Jean',
        prenom='henri',
        adresse='Adresse par défaut 3',
        mail='email2@example.com',
        photo="",
        tel='1234567893',
        password='motdepassepardefaut3',
    )

    User.objects.create(
        nom='Valentin',
        prenom='david',
        adresse='Adresse par défaut 4',
        mail='email2@example.com',
        photo="",
        tel='1234567894',
        password='motdepassepardefaut4',
    )

    User.objects.create(
        nom='hugo',
        prenom='louis',
        adresse='Adresse par défaut 5',
        mail='email2@example.com',
        photo="",
        tel='1234567895',
        password='motdepassepardefaut5',
    )


def add_default_plats(apps, schema_editor):
    Plat = apps.get_model('api', 'Plat') 
    Plat.objects.create(
        dujour=False,
        dessert=False,
        prix=10,  
        ingredient=['patte', 'beurre'],        
        nom='patte au beurre',
        image="",
        id=1,
    )

    Plat.objects.create(
        dujour=True,
        dessert=True,
        prix=10,  
        ingredient='beurre, oeuf, farine, sucre, levure, sel, lait, creme fraiche, sucre glace, cacao, chocolat noir',        
        nom='gateau au chocolat',
        image="",
        id=2,
    )

    Plat.objects.create(
        dujour=True,
        dessert=False,
        prix=10,  
        ingredient='patte, saumon, creme fraiche, citron, sel, poivre, aneth',        
        nom='tagliatelle au saumon',
        image="",
        id=3,
    )

    Plat.objects.create(
        dujour=False,
        dessert=True,
        prix=10,  
        ingredient='pomme, sucre, eau, cannelle',        
        nom='pompot',
        image="",
        id=4,
    )

    Plat.objects.create(
        dujour=False,
        dessert=False,
        prix=10,
        ingredient='knaki, beurre, lait, sel, poivre, pomme de terre, eau',
        nom='purée knaki',
        image="",
        id=5,
    )

    Plat.objects.create(
        dujour=False,
        dessert=False,
        prix=10,
        ingredient='knaki, beurre, lait, sel, poivre, pomme de terre, eau',
        nom='purée knaki',
        image="",
        id=5,
    )


def add_default_commandes(apps, schema_editor):
    Commande = apps.get_model('api', 'Commande') 
    Commande.objects.create(
        prix_total=0, 
        id_client=1,
        id_livreurs=2,
        id_plats=[1,1,1,1,4,4,4,4],
        etat='livré',
    )

    Commande.objects.create(
        prix_total=0, 
        id_client=1,
        id_livreurs=2,
        id_plats=[1,1,1,1,4,4,4,4], 
        etat='livré',
    )

    Commande.objects.create(
        prix_total=0, 
        id_client=1,
        id_livreurs=2,
        id_plats=[1,1,1,1,4,4,4,4], 
        etat='livré',
    )

    Commande.objects.create(
        prix_total=0, 
        id_client=3,
        id_livreurs=2,
        id_plats=[5,5,5,5,5,5,5,5,2,2], 
        etat='livré',
    )


def add_default_livreurs(apps, schema_editor):
    Livreur = apps.get_model('api', 'Livreur') 
    Livreur.objects.create(
        id_user=5,
        localisation="rue de la gare",
        status="occuper",
    )

    Livreur.objects.create(
        id_user=4,
        localisation="rue de la paix",
        status="libre",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_plats),
        migrations.RunPython(add_default_users),
        migrations.RunPython(add_default_commandes),
        migrations.RunPython(add_default_livreurs),
    ]
