# Generated by Django 4.1.11 on 2023-09-21 21:30

from django.db import migrations

def add_default_users(apps, schema_editor):
    User = apps.get_model('api', 'User')

    user1 = User.objects.create(
        nom="ccdc",
        prenom="fabien",
        adresse="4 rue de la paix",
        mail="fabien@fabien.fr",
        photo="",
        tel="1234567890",
        password="$2a$12$Q8fxQFuFP/XoObZpStdvw.lAkVJMmc6yf7bLSX2oX2ovYQsrKaqeO",
        username="fabien@fabien.fr",
    )
    user1.roles.add(1)
    user1.roles.add(3)
    user1.save()
    
    User.objects.create(
        nom='Kevin',
        prenom='autre',
        adresse='5 avenue de paris',
        mail='email1@example.com',
        photo="",
        tel='1234567892',
        password='motdepassepardefaut2',
        username="email1@example.com",
    )

    User.objects.create(
        nom='Jean',
        prenom='henri',
        adresse='Adresse par défaut 3',
        mail='email2@example.com',
        photo="",
        tel='1234567893',
        password='motdepassepardefaut3',
        username='email2@example.com',
    )

    User.objects.create(
        nom='Valentin',
        prenom='david',
        adresse='Adresse par défaut 4',
        mail='email3@example.com',
        photo="",
        tel='1234567894',
        password='motdepassepardefaut4',
        username='email3@example.com',
    )

    User.objects.create(
        nom='hugo',
        prenom='louis',
        adresse='Adresse par défaut 5',
        mail='email4@example.com',
        photo="",
        tel='1234567895',
        password='motdepassepardefaut5',
        username='email4@example.com',
    )


def add_default_plats(apps, schema_editor):
    Plat = apps.get_model('api', 'Plat') 
    Plat.objects.create(
        dujour=False,
        dessert=False,
        prix=10,  
        ingredient='patte, beurre',        
        nom='patte au beurre',
        image="",
        id=1,
    )

    Plat.objects.create(
        dujour=True,
        dessert=True,
        prix=10,  
        ingredient='beurre, oeuf, farine, sucre, levure, sel, lait, creme fraiche, sucre glace, cacao, chocolat noir',        
        nom='gateau au chocolat',
        image="",
        id=2,
    )

    Plat.objects.create(
        dujour=True,
        dessert=False,
        prix=10,  
        ingredient='patte, saumon, creme fraiche, citron, sel, poivre, aneth',        
        nom='tagliatelle au saumon',
        image="",
        id=3,
    )

    Plat.objects.create(
        dujour=False,
        dessert=True,
        prix=10,  
        ingredient='pomme, sucre, eau, cannelle',        
        nom='pompot',
        image="",
        id=4,
    )

    Plat.objects.create(
        dujour=False,
        dessert=False,
        prix=10,
        ingredient='knaki, beurre, lait, sel, poivre, pomme de terre, eau',
        nom='purée knaki',
        image="",
        id=5,
    )


def add_default_livreurs(apps, schema_editor):
    Livreur = apps.get_model('api', 'Livreur') 
    User = apps.get_model('api', 'User')

    Livreur.objects.create(
        user=User.objects.get(pk=1),
        localisation="rue de la gare",
        status="libre",
    )

    Livreur.objects.create(
        user=User.objects.get(pk=2),
        localisation="rue de la paix",
        status="libre",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_plats),
        migrations.RunPython(add_default_users),
        migrations.RunPython(add_default_livreurs),
    ]
