# Generated by Django 4.1.11 on 2023-09-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230921_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='userlivreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livreur'),
        ),
    ]
